# Generated by Django 3.2.6 on 2021-09-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='email',
        ),
    ]
