# Generated by Django 3.2.6 on 2021-10-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='teacher',
        ),
    ]
