# Generated by Django 3.2.6 on 2021-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
