# Generated by Django 3.2.6 on 2021-09-10 21:51

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210909_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityimage',
            name='images',
        ),
        migrations.AddField(
            model_name='activityimage',
            name='image',
            field=models.FileField(null=True, upload_to=activities.models.get_upload_path),
        ),
    ]
