# Generated by Django 3.2.6 on 2021-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digicrecheuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'manager'), (2, 'teacher'), (3, 'parent')], default='3'),
        ),
    ]
