# Generated by Django 3.2.6 on 2021-08-11 11:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_digicrecheuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digicrecheuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='digicrecheuser',
            name='county',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='digicrecheuser',
            name='town_or_city',
            field=models.CharField(max_length=40),
        ),
    ]
