# Generated by Django 3.2.6 on 2021-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210811_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digicrecheuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Teacher'), (3, 'Parent')], default='3'),
        ),
    ]
