# Generated by Django 3.2.6 on 2021-08-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_manager'),
        ('accounts', '0006_alter_digicrecheuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='digicrecheuser',
            name='school',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to='schools.school'),
        ),
    ]
