# Generated by Django 3.2.6 on 2021-09-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_manager'),
        ('accounts', '0009_alter_digicrecheuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digicrecheuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institution', to='schools.school'),
        ),
    ]
