# Generated by Django 3.2.6 on 2021-10-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_teacher'),
        ('accounts', '0010_alter_digicrecheuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='digicrecheuser',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='rooms.room'),
        ),
    ]
