# Generated by Django 3.2.6 on 2021-10-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_email'),
        ('accounts', '0012_digicrecheuser_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digicrecheuser',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Leave blank if you are a manager.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institution', to='schools.school'),
        ),
    ]
