# Generated by Django 3.2.6 on 2021-10-19 14:08

from django.db import migrations, models
import pupils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='photo',
            field=models.FileField(null=True, upload_to=pupils.models.get_upload_path),
        ),
    ]
