# Generated by Django 3.2.6 on 2021-10-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_icon'),
        ('pupils', '0002_pupil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupils', to='rooms.room'),
        ),
    ]
